<?php

/**
 * The main index template file
 *
 * @package Cornerstone
 * @subpackage Core Cornerstone Theme
 */

// Set the meta/og information for the page
$pageMetaTitle = $data->site_name;
$pageMetaDescription = "Cornerstone example index page.";
$pageMetaKeywords = "cornerstone, php, framework";
$pageMetaImage = get_site_url('img/site_ogp_image.png');
$pageMetaCanonical = get_site_url();
$pageMetaType = "website";

// Set any page injected values
$pageBodyClassID = 'class="cs-page cs-components"';
$pageHeadExtras = '';
$pageFooterExtras = '<script src="https://unpkg.com/@popperjs/core@2"></script><script src="https://unpkg.com/tippy.js@6"></script>';

// Load html head
require(get_theme_path('head.php'));
// Load html layout
require(get_theme_path('layout.php')); ?>

<!-- End Header ~#~ Start Main -->
<section id="cs-main">
  <div class="csc-wrapper">
    <h1 class="cs-h1">Cornerstone starter template</h1>
    <p class="cs-body1">Use this document as a way to quickly start any new project.</p>
    <p class="cs-body2">This document is generated by the 'system/controllers/page', 'system/views/pages/index.vw', and 'system/views/theme/*' files.</p>
    <div class="csc-container cs-mt-5 cs-p-3">
      <h2 class="cs-h3">Want to learn more?</h2>
      <p class="cs-body1">For more information on Cornerstone, check out the <a href="https://github.com/dpDesignz/cornerstone" target="_blank" title="Cornerstone PHP Framework Website">Github repository</a>.</p>
    </div>
  </div>
</section>
<!-- End Main ~#~ Start Footer -->

<?php
// Load html footer
require(get_theme_path('footer.php')); ?>